#!/bin/sh
export _JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java

export PATH=$PATH":/home/mzanic/.local/bin/scripts:/home/mzanic/.local/bin/scripts/status_bar"
export PATH=$PATH":/home/mzanic/.local/bin"
export PATH="$PATH:${$(find $HOME/.local/bin -not -path '*/\.git/*' -type d -printf %p:)%%:}"
export PATH="$PATH:$HOME/.emacs.d/bin"
export PATH="$PATH:$HOME/.dotnet"

export DOTS="$HOME/.config/.dotfiles"
export EDITOR="emacsclient -c -n "
export TERMINAL='alacritty'
export BROWSER='brave'

export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"

export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export LESSHISTFILE="-"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export GRADLE_USER_HOME="$XDG_DATA_HOME/gradle"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"
#export GNUPGHOME="$XDG_DATA_HOME"/gnupg

export EMACSDIR="$XDG_CONFIG_HOME/emacs"
export DOOMDIR="$XDG_CONFIG_HOME/doom"
export CABAL_CONFIG="$XDG_CONFIG_HOME"/cabal/config
export CABAL_DIR="$XDG_CACHE_HOME"/cabal

export CARGO_HOME="$XDG_DATA_HOME"/cargo
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
export STACK_ROOT="$XDG_DATA_HOME"/stack
