#!/bin/sh

MANAGER='xmonad'

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

while :; do
    #ssh-agent "$HOME/.local/bin/xmonad"
    ssh-agent "/etc/xmonad/xmonad-x86_64-linux"
done
