name: lvt-xmonad
version: 69
synopsis: XMonad Rocks!
license: MIT
author: Mislav Zanic
maintainer: mislavzanic3@gmail.com

ghc-options:
  -Wall
  -Wcompat
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wredundant-constraints
  -O2

source-dirs: src

dependencies:
  - X11
  - base
  - time
  - unix
  - xmobar
  - xmonad
  - libmpd
  - process
  - filepath
  - directory
  - containers
  - utf8-string
  - xmonad-contrib

executables:
  xmonad:
    main: xmonad.hs
  xmobar:
    main: xmobar.hs
    ghc-options:
      -rtsopts
      -threaded
      -with-rtsopts=-N
